name: VeldPlugin
version: '${version}'
main: com.charlotte04.veldplugin.VeldPlugin
api-version: 1.18
commands:
  veld:
    aliases: [ve]
  veldsetting:
    aliases: [veset]
  tag:
    aliases: [vetag]
